### ISSUE TITLE
API flaking out?

### ISSUE THREAD

**Issue by jquinby** [michaelwoods/onstar2mqtt#260]
I've been getting some timeouts pretty consistently for awhile now, running 1.5.4 in a docker container for the HA integration. Was wondering if the GM API is just flaky as all get out or if there's something that's been changed on their end preventing access. 

Here's what I'm seeing in the docker log; VIN is redacted. 

```
info: Vehicle request status {"status":"success"}                                                                                                                             
info: Connecting to MQTT {"config":{"username":"","will":{"payload":"false","retain":true,"topic":"homeassistant/VIN/available"}},"url":"mqtt://10.0.1.54:1883"}
info: Connected to MQTT                                                                                                                                                       
info: Subscribed to command topic {"topic":"homeassistant/VIN/command"}                                                                                         
info: Requesting diagnostics                                                                                                                                                  
error: Error {"error":{"message":"Command Timeout","request":{"body":"{\"diagnosticsRequest\":{\"diagnosticItem\":[\"LAST TRIP FUEL ECONOMY\",\"ENERGY EFFICIENCY\",\"HYBRID B
ATTERY MINIMUM TEMPERATURE\",\"EV ESTIMATED CHARGE END\",\"LIFETIME ENERGY USED\",\"EV BATTERY LEVEL\",\"EV PLUG VOLTAGE\",\"HOTSPOT CONFIG\",\"ODOMETER\",\"HOTSPOT STATUS\",
\"LIFETIME EV ODOMETER\",\"CHARGER POWER LEVEL\",\"EV PLUG STATE\",\"EV CHARGE STATE\",\"TIRE PRESSURE\",\"AMBIENT AIR TEMPERATURE\",\"LAST TRIP DISTANCE\",\"INTERM VOLT BATT
 VOLT\",\"GET COMMUTE SCHEDULE\",\"EV SCHEDULED CHARGE START\",\"VEHICLE RANGE\"]}}","contentType":"application/json; charset=UTF-8","headers":{},"method":1,"url":"https://ap
i.gm.com/api/v1/account/vehicles/VIN/commands/diagnostics"},"response":{"data":{"commandResponse":{"requestTime":"2023-03-20T17:33:12.128Z","status":"inProgress
","type":"diagnostics","url":"https://api.gm.com/api/v1/account/vehicles/VIN/requests/30862447338"}},"headers":{"connection":"keep-alive","content-type":"applic
ation/json;charset=UTF-8","date":"Mon, 20 Mar 2023 17:33:12 GMT","push-response":"Rejected 30","request-context":"appId=cid-v1:a7e19842-5b19-4b47-a9cf-85cc6e87a746","transfer
-encoding":"chunked"},"status":202,"statusText":"Accepted"},"stack":"Error: Command Timeout\n    at RequestService.<anonymous> (/app/node_modules/onstarjs/dist/index.js:570:3
5)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/onstarjs/dist/index.js:32:58)\n    at process.processTicksAndRejections (node:internal/process/ta
sk_queues:95:5)"}} 
```
The GM app continues to work, as far as I can tell. Anyone else, or just me?

**Comment by stamanf** [comment]
I have the same problem since yesterday.
Plus if I try to manually go in my onstar account, I get a 404 error.  Onstar tech support is useless.

Any clues ?

**Comment by tbclark3** [comment]
I started getting errors today, and the docker app crashes consistently after returning a 404 error.  My Android app is also still working.

**Comment by tbclark3** [comment]
That solved the problem. Your build works beautifully.  Thank you!

**Comment by stamanf** [comment]
Solved my issue as well.  Thanks !!!!

**Comment by michaelwoods** [comment]
v1.5.5 tagged with latest onstarjs
